### ISSUE TITLE
Criar comando /rede

### ISSUE THREAD

**Issue by ArTombado** [SmookeyDev/PortalNano_bot#9]
Criar um comando que mostre os seguintes status:
-Blocos confirmados/checados
-Quantidade de contas no total
-Quantidade de tempo restante para zerar o backlog(talvez, nesse caso seria um status temporario)
-Supply disponivel(talvez tambem, por ser uma metrica meio inutil pode pecar no tempo pra processar o request)

**Comment by ArTombado** [comment]
Api da nanocrawler não aceita o request de frontier_count(quantidade de contas), talvez devemos colocar apenas a quantidade de blocos?

**Comment by SmookeyDev** [comment]
Pull Request de adição do comando aceita, fechando issue.
